plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.0.21'
    id("org.jetbrains.kotlinx.kover") version "0.9.1"
}

group = 'lab2'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}

kover {
    reports {
        total {
            xml {
                true
            }
        }
        verify {
            rule {
                bound{
                    minValue = 75
                }
            }
        }
    }
}
