plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.0.21'
    id("org.jetbrains.kotlinx.kover") version "0.9.1"
}

group = 'lab2'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.testcontainers:testcontainers:1.19.5'
    testImplementation 'org.testcontainers:junit-jupiter:1.19.3'
    implementation 'redis.clients:jedis:5.1.0'
    testImplementation 'ch.qos.logback:logback-classic:1.4.14'
    testImplementation 'org.slf4j:slf4j-api:2.0.13'
}

test {
    useJUnitPlatform()
}

kover {
    reports {
        total {
            xml {
                true
            }
        }
        verify {
            rule {
                bound{
                    minValue = 75
                }
            }
        }
    }
}
